apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server
  labels:
    app: simple-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-server
  template:
    metadata:
      name: simple-server
      labels:
        app: simple-server
    spec:
      containers:
        - name: simple-server
          image: titanabrian/simple-server:0.1.2-alpha
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
